### ISSUE TITLE
Android menu does not launch

### ISSUE THREAD

**Issue by developer9969** [RadekVyM/Gadgets-Store-App#2]
Hi Simple love what you have done,
It did work in the past when I tried few months ago,

Launched android emulator tapped on burger bar and nothing - menu does not show

**Comment by RadekVyM** [comment]
Hi @developer9969,
thanks for noticing the issue. On Android, there is currently a problem with changing a value of the `InputTransparent` property in .NET MAUI. I updated the app and it should be better now.

**Comment by developer9969** [comment]
Hey- thanks for fixing this quickly - I want to do some animation when a menu is open and integrate with my shell stuff and see how you do it and what I need to do to integrate in my app
